### PR TITLE
Change the readme to render checkboxes

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Review by killercup — APPROVED** [review]
LGTM!

Did add me to bors, @vitiral? Let's try it!

bors r+

(@notriddle, be honest: do you stalk bors' queue for new open source projects to contribute to? If so: That's awesome! Thanks!)

Edit: Awwww (but it's fine I'm probably not gonna do much in this orga right now because I'm busy doing other stuff anyway 😄)

**Comment by notriddle** [comment]
> Did add me to bors, @vitiral? Let's try it!

Visit https://app.bors.tech/repositories/ to check your privilege without trying to exercise it.

> (@notriddle, be honest: do you stalk bors' queue for new open source projects to contribute to? If so: That's awesome! Thanks!)

Yes.

Specifically, I use [this tool](https://github.com/notriddle/show-recent-activity-for-github-bot) to track the comments it makes at the GitHub level. It also works for stalking any other GitHub app (like Greenkeeper and TaskCluster).

I primarily track it to make sure an expected amount of activity is being generated (if bors suddenly doesn't post anything for a day, it's probably down) and to see where people are being tripped up (like you just were).

**Comment by vitiral** [comment]
should be good to go now

bors r= @killercup

**Comment by vitiral** [comment]
I added the missing files to `master`, looks to be working now.

**Comment by vitiral** [comment]
bors retry

**Pull request merged**
