### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by vitiral**
bors r? @killercup

### CODE REVIEW

**Comment by killercup** [comment]
Ehh, not sure what process you have in mind, but I may need more than a day to have time to review a PR ;)

(Also, why the workaround for bors?)

**Comment by vitiral** [comment]
Sorry about that. I'm working on using `ergo` in artifact to work any kinks and thought I would take advantage of the "alpha" level of the crate. I shouldn't do that though.

It looked like appveyor was going to fail for some weird reason so I just skipped it for now.

**Comment by killercup** [comment]
No worries, just wanted to let you know I saw this (too late) :)

**Pull request merged**
