### PR TITLE
Consolodate

### PR DESCRIPTION
**Pull request by vitiral**
This consolodates the various git reposotories into a single workspace. I don't think there are any disadvantages to this.

I will delete the other repositories after this is merged.

@killercup let me know if you have any objections.

I have to say, I'm a HUGE fan of workspaces!

### CODE REVIEW

**Comment by vitiral** [comment]
I followed this guide for consolodating:

https://stackoverflow.com/a/20974621/1036670

I also edited that answer with a helpful script

```
PROJ=<your-repo-name>
echo PROJ="merging $PROJ with master" && \
  git remote add -f $PROJ git@github.com:<your-user-name>/${PROJ}.git && \
  git checkout -b ${PROJ}_branch $PROJ/master && \
  mkdir $PROJ && git mv $(ls -I $PROJ) $PROJ && \
  rm -f .gitignore .travis* && \
  git commit -am "move files to subdir" && \
  git checkout master && \
  git merge ${PROJ}_branch --allow-unrelated-histories
```

**Comment by killercup** [comment]
Cargo workspaces are great!

That SO answer confuses me. I've used `git subtree add -P <crate-name> <repo-url> <branch>` – which is far easier :) – and all the history stayed intact AFAIK.

**Comment by vitiral** [comment]
Lol, that would have been good to know! So you approve of this change?

**Review by killercup — APPROVED** [review]
Sure, go right ahead!

I haven't tested that all crates still work and have the correct links set up or anything but trust that we can get it right before the next releases :)

**Pull request merged**
