### PR TITLE
update README with purpose and roadmap

### PR DESCRIPTION
**Pull request by vitiral**
@bors r=killercup

@autron you might be interested as well :)

### CODE REVIEW

**Comment by vitiral** [comment]
bors r= @killercup

**Comment by vitiral** [comment]
with @autron's recent 2018 roadmap I'm itching to get this merged and anounce the initiave.

**Comment by vitiral** [comment]
bors retry

**Comment by vitiral** [comment]
bors try

**Comment by vitiral** [comment]
@killercup I'm going ahead and merging, let me know if you have any objections (but I think this is all in line with what we've discussed).

**Comment by killercup** [comment]
I think you wanted to ping @aturon :)

**Pull request merged**
